apiVersion: v1
kind: Service
metadata:
  #name: headless-service
  name: api
spec:
  clusterIP: None # <-- Don't forget!!
  selector:
    app: api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
